"""
Testing utilities and fixtures for cookie validator.
Provides helper functions for testing validation logic.
"""

import json
from pathlib import Path
from typing import Dict, Any
import tempfile


class CookieTestData:
    """Sample cookie data for testing."""
    
    NETSCAPE_SAMPLE = """# Netscape HTTP Cookie File
# Generated by tests
.cloud.digitalocean.com	TRUE	/	TRUE	0	__Host-session	session_token_12345
.cloud.digitalocean.com	TRUE	/	TRUE	0	auth_token	auth_token_67890
.cloud.digitalocean.com	TRUE	/	FALSE	0	preferences	pref_value_123
"""
    
    JSON_SAMPLE = [
        {
            "domain": ".cloud.digitalocean.com",
            "name": "__Host-session",
            "value": "session_token_12345",
            "path": "/",
            "secure": True,
            "httpOnly": True,
            "expirationDate": 1735689600
        },
        {
            "domain": ".cloud.digitalocean.com",
            "name": "auth_token",
            "value": "auth_token_67890",
            "path": "/",
            "secure": True,
            "httpOnly": True,
            "expirationDate": 1735689600
        }
    ]
    
    @staticmethod
    def create_netscape_file(path: Path) -> None:
        """Create sample Netscape format cookie file."""
        path.write_text(CookieTestData.NETSCAPE_SAMPLE)
    
    @staticmethod
    def create_json_file(path: Path) -> None:
        """Create sample JSON format cookie file."""
        path.write_text(json.dumps(CookieTestData.JSON_SAMPLE, indent=2))
    
    @staticmethod
    def create_test_folder() -> Path:
        """Create temporary folder with test cookies."""
        temp_dir = Path(tempfile.mkdtemp())
        
        # Create test files
        CookieTestData.create_netscape_file(temp_dir / "cookies.txt")
        CookieTestData.create_json_file(temp_dir / "cookies.json")
        
        return temp_dir


if __name__ == "__main__":
    # Create and print sample data
    print("Netscape Format Sample:")
    print(CookieTestData.NETSCAPE_SAMPLE)
    print("\nJSON Format Sample:")
    print(json.dumps(CookieTestData.JSON_SAMPLE, indent=2))
